fix(FEC-10041): Allow IMA and IMA DAI to be used in parallel
kaltura/playkit-js-ima-dai pull request #54
Opened 2021-02-01 08:42 UTC by Yuvalke

### Description of the Changes

Issue: load promise return the incorrect promise.
ima dai SDK fires ad_break_start and ad_start after load and before play request.
Solution: return a new promise on load which resolves or rejects on engine load rejection or resolves.
delay the ima dai SDK event to fires after play instead of the incorrect event after load which causes incorrect behavior on the player.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-02-01 18:56 UTC, OrenMe commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
off topic - but seem like we are not raising an error here at all, if so we need to see how to raise a recoverable error so app/analytics can register to.

2021-02-01 18:58 UTC, OrenMe commented on src/ima-dai.js
> +    this.eventManager.listenOnce(this._engine, EventType.PLAY, () => this._onFirstPlayRequest());
we have first_play for this as well

2021-02-01 18:59 UTC, OrenMe commented on src/ima-dai.js
> +  _onFirstPlayRequest(): void {
let's keep some order in the file, add near the other `_onEvent` handlers

2021-02-01 19:17 UTC, Yuvalke commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
we're using the engine load, we're rasing error on player anyway when promise reject

2021-02-01 19:20 UTC, Yuvalke commented on src/ima-dai.js
> +    this.eventManager.listenOnce(this._engine, EventType.PLAY, () => this._onFirstPlayRequest());
IMA DAI engine decorator filter it out and dispatch when ad finished from the player(on this level we have the first play), that why I added a register to engine level

2021-02-01 19:22 UTC, Yuvalke commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
Do you mean to expose an error for IMA SDK failure? after getStreamUrl otherwise my comment above will handle it

2021-02-01 19:57 UTC, OrenMe requested changes

2021-02-01 19:57 UTC, OrenMe commented on src/ima-dai.js
> -      this._dispatchAdEvent(EventType.AD_PAUSED);
we can keep the original function and its name and add the logic to it, no benefit in adding another wrapper around the logic.
This is the same as we have in current ima dai event manager which uses the queue manager.

2021-02-01 19:57 UTC, OrenMe commented on src/ima-dai.js
> +    }
if we are starting to use this pattern in more places then lets DRY it and add to queue an execute method that is given a handler and does the iteration:
```
execute(handler){
  if (this._queue.size() > 0) {
      while (!this._queue.isEmpty()) {
        handler(this._queue.pop())
      }
    }
}
```
```
execute(item=>{
  const {name, payload} = item;
  this._dispatchAdEvent(name, payload);
}) 
```

2021-02-01 19:57 UTC, OrenMe commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
In the reject of the `getStreamUrl` we fallback to original URL silently so if I understand we are not exposing an error at all

2021-02-03 09:08 UTC, Yuvalke commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
Right, but if we want to handle it I think we need to do it in separate task

2021-02-04 10:11 UTC, yairans requested changes

2021-02-04 10:11 UTC, yairans commented on src/ima-dai-engine-decorator.js
> +    return new Promise((resolve, reject) => {
why this needed?

2021-02-04 10:14 UTC, yairans approved these changes

2021-02-04 10:20 UTC, Yuvalke commented on src/ima-dai.js
> +      this.eventManager.listen(this.player, EventType.LOADED_METADATA, () => this._onLoadedMetadata());
cause on the same video you get loaded_metadata for the ads before yours when it's listening to the engine.

2021-02-04 10:21 UTC, Yuvalke commented on src/ima-dai-engine-decorator.js
> +    return new Promise((resolve, reject) => {
cause you return it's not resolved when the engine promise resolve it resolved when you get the URL to play.

2021-02-04 10:22 UTC, Yuvalke commented on src/ima-dai.js
> +      this.eventManager.listen(this.player, EventType.LOADED_METADATA, () => this._onLoadedMetadata());
so you basically handle it twice and this is a mistake

2021-02-04 10:40 UTC, yairans submitted a review, later dismissed

2021-02-04 10:43 UTC, OrenMe commented on src/ima-dai-engine-decorator.js
> +          this._logger.error(e);
Please open a ticket with details

2021-02-04 10:47 UTC, OrenMe commented on src/ima-dai.js
> +  _dispatchEventsOnFirstPlay(): void {
If not used then can be removed

2021-02-04 10:48 UTC, OrenMe commented on src/ima-dai.js
> +  _dispatchEventsOnFirstPlay(): void {
I see it is used, so disregard

2021-02-04 11:38 UTC, yairans approved these changes

2021-02-04 12:14 UTC, OrenMe approved these changes

2021-02-04 12:33 UTC, merged