feat(FEC-10264): add support for IMA DAI UiSettings - locale
kaltura/playkit-js-ima-dai pull request #57
Opened 2021-02-15 14:04 UTC by Yuvalke

### Description of the Changes

Add uiSetting for IMA DAI with locale config.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-02-15 18:31 UTC, yairans requested changes

2021-02-15 18:31 UTC, yairans commented on src/ima-dai.js
> +      if (Object.prototype.hasOwnProperty.call(this.config, 'locale')) {
```suggestion
      if (this.config.locale) {
```

2021-02-16 09:08 UTC, Yuvalke commented on src/ima-dai.js
> +      if (Object.prototype.hasOwnProperty.call(this.config, 'locale')) {
Why does it important? I saw we did it the same for IMA so I guessed there is a reason - the only difference is to accept the empty string on my check.
I guess we don't want to be dependent on the value itself, anyway it's not so important just kept the same check on both.

2021-02-17 08:41 UTC, yairans commented on src/ima-dai.js
> +      if (Object.prototype.hasOwnProperty.call(this.config, 'locale')) {
it's weird. i dont see any reason to write the simple not null condition like that.

2021-02-21 09:34 UTC, yairans approved these changes

2021-02-21 09:35 UTC, merged