fix(FEC-11031): DAI doesn't work in change media after failure
kaltura/playkit-js-ima-dai pull request #59
Opened 2021-02-23 13:17 UTC by yairans

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-02-23 13:18 UTC, Yuvalke approved these changes

2021-02-23 13:18 UTC, Yuvalke requested changes

2021-02-23 13:18 UTC, Yuvalke commented on src/ima-dai-engine-decorator.js
> +    this._plugin.player.addEventListener(this._plugin.player.Event.PLAYER_RESET, () => {
we need to remove it on destroy

2021-02-23 14:11 UTC, yairans commented on src/ima-dai-engine-decorator.js
> +    this._plugin.player.addEventListener(this._plugin.player.Event.PLAYER_RESET, () => {
on destroy all player listeners become irrelevant

2021-02-23 14:21 UTC, merged

2021-02-26 07:23 UTC, OrenMe commented on src/ima-dai-engine-decorator.js
> +    this._plugin.player.addEventListener(this._plugin.player.Event.PLAYER_RESET, () => {
Why not use the base plugin reset method?